version: '3'
services:
  sitewatcher-redis:
    image: redis:latest
    container_name: sitewatcher-redis
  sitewatcher:
    container_name: sitewatcher
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - crontab_template=${CRONTAB_TEMPLATE}
        - redis_host=sitewatcher-redis
        - redis_port=6379
        - logs_dir=/logs
        - slack_bot_token=${SLACK_BOT_TOKEN}
    volumes:
      - type: bind
        source: ${HOST_LOGS_DIR}
        target: /logs
