version: '3'
services:
  sitewatcher-redis:
    image: redis:latest
    container_name: sitewatcher-redis
  sitewatcher:
    container_name: sitewatcher
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - crontab_template=${CRONTAB_TEMPLATE:-sample.crontab_template}
        - redis_host=sitewatcher-redis
        - redis_port=6379
        - logs_dir=/logs
    volumes:
      - type: bind
        source: ./logs
        target: /logs
